"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from urllib.parse import urlsplit

from django.core.exceptions import ImproperlyConfigured

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-development-only-change-me',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() == 'true'
if not DEBUG and (SECRET_KEY.startswith('django-insecure-') or len(SECRET_KEY) < 50):
    raise ImproperlyConfigured('Set a production DJANGO_SECRET_KEY of at least 50 characters.')

APP_BASE_URL = os.environ.get('APP_BASE_URL', '').rstrip('/')
STORAGE_DIR = Path(os.environ.get('STORAGE_DIR') or BASE_DIR)
DATA_WORKER_ENABLED = os.environ.get('DATA_WORKER_ENABLED', 'false').lower() == 'true'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        'DJANGO_ALLOWED_HOSTS',
        '127.0.0.1,localhost',
    ).split(',')
    if host.strip()
]
if APP_BASE_URL:
    ALLOWED_HOSTS.append(urlsplit(APP_BASE_URL).hostname)
CSRF_TRUSTED_ORIGINS = [APP_BASE_URL] if APP_BASE_URL else []
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG
SECURE_REDIRECT_EXEMPT = [r'^healthz$']
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
# The managed edge contract covers this exact hostname, not arbitrary child hosts
# or browser preload enrollment. Keep all other deployment warnings actionable.
SILENCED_SYSTEM_CHECKS = ['security.W005', 'security.W021']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'config',
    'places.apps.PlacesConfig',
    'recommendations',
    'users.apps.UsersConfig',
]

AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'config.cors.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('DJANGO_DB_PATH', str(STORAGE_DIR / 'db.sqlite3')),
        'OPTIONS': {'timeout': 20, 'transaction_mode': 'IMMEDIATE'},
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True

CROWD_ESTIMATION_ENABLED = os.environ.get('CROWD_ESTIMATION_ENABLED', 'true').lower() == 'true'
CROWD_DISABLE_TREND_HORIZONS = [int(v) for v in os.environ.get('CROWD_DISABLE_TREND_HORIZONS', '').split(',') if v.strip() in ('1', '2', '3')]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = STORAGE_DIR / 'media'
CORS_ALLOWED_ORIGINS = [value.strip() for value in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if value.strip()]


# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework / JWT

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'ROTATE_REFRESH_TOKENS': False,
}

# Google OAuth (구글 로그인 ID Token 검증용)
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')

# Explainable starting weights and weather thresholds; adjust after product validation.
RECOMMENDATION_WEIGHTS = {
    'distance': 0.30, 'category': 0.15, 'crowd': 0.20,
    'weather': 0.25, 'indoor_outdoor': 0.10,
}
CROWD_FRESH_MINUTES = 15
CROWD_FULL_WEIGHT_MINUTES = 30
CROWD_MAX_AGE_MINUTES = 45
CROWD_DELAYED_WEIGHT_FACTOR = 0.5
WEATHER_THRESHOLDS = {'wind_mps': 9.0, 'hot_c': 33.0, 'cold_c': -10.0}
# A development freshness allowance: KMA village forecasts are issued every
# three hours. One missed issue is tolerated; fetched_at never extends it.
WEATHER_MAX_ISSUE_AGE_HOURS = 5
# This is a ranking distance scale, independent of the request's hard radius.
RECOMMENDATION_DISTANCE_SCALE_KM = 2.5
# Retain a real distance cost beyond the close neighborhood, even when the
# request's hard radius is large (for example 100 km).
RECOMMENDATION_DISTANCE_GUARD_FREE_KM = 5.0
RECOMMENDATION_DISTANCE_GUARD_SCALE_KM = 20.0
RECOMMENDATION_NAME_RULE_WEIGHT_FACTOR = 0.5
RECOMMENDATION_DESCRIPTION_RULE_WEIGHT_FACTOR = 0.75
RECOMMENDATION_LUNA_VALIDATED_WEIGHT_FACTOR = 0.5
RECOMMENDATION_CONTEXT_CACHE_SECONDS = max(
    0, min(300, int(os.environ.get('RECOMMENDATION_CONTEXT_CACHE_SECONDS', '60')))
)
