# Generated by Django 6.0.6 on 2026-08-09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                (
                    'subcategory',
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ('region_code', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                (
                    'latitude',
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    'longitude',
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    'indoor_outdoor',
                    models.CharField(
                        choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')],
                        max_length=7,
                    ),
                ),
                (
                    'open_status',
                    models.CharField(
                        blank=True,
                        choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')],
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    'avg_rating',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
