# Generated by Django 6.0.6 on 2026-08-17 12:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='indoor_outdoor',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='unknown', max_length=7),
        ),
        migrations.CreateModel(
            name='CrowdArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('tour_api', 'Korea Tourism Organization TourAPI'), ('seoul_realtime', 'Seoul Real-time Population')], max_length=30)),
                ('external_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('region_code', models.CharField(blank=True, max_length=20)),
                ('raw_data', models.JSONField(default=dict)),
                ('last_synced_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_crowd_area_external_id')],
            },
        ),
        migrations.CreateModel(
            name='CrowdData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('crowd_level', models.CharField(choices=[('relaxed', 'Relaxed'), ('normal', 'Normal'), ('busy', 'Busy'), ('crowded', 'Crowded'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('crowd_message', models.TextField(blank=True)),
                ('crowd_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('population_min', models.PositiveIntegerField(blank=True, null=True)),
                ('population_max', models.PositiveIntegerField(blank=True, null=True)),
                ('is_replaced', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crowd_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='places.crowdarea')),
            ],
            options={
                'indexes': [models.Index(fields=['crowd_area', '-observed_at'], name='places_crow_crowd_a_f93896_idx')],
                'constraints': [models.UniqueConstraint(fields=('crowd_area', 'observed_at'), name='unique_crowd_observation'), models.CheckConstraint(condition=models.Q(('population_min__isnull', True), ('population_max__isnull', True), ('population_min__lte', models.F('population_max')), _connector='OR'), name='crowd_population_range_is_valid')],
            },
        ),
        migrations.CreateModel(
            name='PlaceCrowdArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_method', models.CharField(choices=[('manual', 'Manual'), ('coordinate', 'Coordinate'), ('source', 'External source')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crowd_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_mappings', to='places.crowdarea')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowd_area_mappings', to='places.place')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('place', 'crowd_area'), name='unique_place_crowd_area')],
            },
        ),
        migrations.CreateModel(
            name='PlaceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('tour_api', 'Korea Tourism Organization TourAPI'), ('seoul_realtime', 'Seoul Real-time Population')], max_length=30)),
                ('external_id', models.CharField(max_length=255)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('source_category', models.CharField(blank=True, max_length=100)),
                ('source_address', models.CharField(blank=True, max_length=500)),
                ('source_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('source_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('match_status', models.CharField(choices=[('new', 'New'), ('matched', 'Matched'), ('manual_review', 'Manual review'), ('inactive', 'Inactive')], default='new', max_length=20)),
                ('raw_data', models.JSONField(default=dict)),
                ('last_synced_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='places.place')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'match_status'], name='places_plac_source_fc9a97_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_place_source_external_id'), models.CheckConstraint(condition=models.Q(models.Q(('match_status', 'matched'), ('place__isnull', False)), models.Q(('match_status', 'matched'), _negated=True), _connector='OR'), name='matched_place_source_has_place')],
            },
        ),
    ]
