# Generated by Django 6.0.6 on 2026-08-17 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_indoor_outdoor_crowdarea_crowddata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('homepage_url', models.URLField(blank=True, max_length=1000)),
                ('first_image_url', models.URLField(blank=True, max_length=1000)),
                ('opening_hours', models.TextField(blank=True)),
                ('holiday_info', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('merged_summary_source', models.CharField(blank=True, choices=[('tour_api', 'Korea Tourism Organization TourAPI'), ('seoul_realtime', 'Seoul Real-time Population')], max_length=30)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='places.place')),
            ],
        ),
    ]
