# Generated by Django 6.0.6 on 2026-09-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_placeinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='indoor_outdoor_evidence',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='indoor_outdoor_source',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='place',
            name='indoor_outdoor',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('mixed', 'Mixed')], default='unknown', max_length=7),
        ),
        migrations.CreateModel(
            name='DataJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('target_key', models.CharField(max_length=120)),
                ('dedupe_key', models.CharField(max_length=180, unique=True)),
                ('lane', models.CharField(default='regular', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('payload', models.JSONField(default=dict)),
                ('cursor', models.PositiveIntegerField(default=1)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('run_after', models.DateTimeField()),
                ('leased_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'run_after'], name='places_data_status_fab2a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProviderCallBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('lane', models.CharField(max_length=12)),
                ('used', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'date', 'lane'), name='unique_provider_daily_lane')],
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='kma_vilage', max_length=30)),
                ('grid_x', models.PositiveSmallIntegerField()),
                ('grid_y', models.PositiveSmallIntegerField()),
                ('issued_at', models.DateTimeField()),
                ('target_at', models.DateTimeField()),
                ('precipitation_type', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('wind_mps', models.FloatField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['grid_x', 'grid_y', 'target_at', '-issued_at'], name='places_weat_grid_x_3c679a_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'grid_x', 'grid_y', 'issued_at', 'target_at'), name='unique_weather_forecast_target')],
            },
        ),
    ]
