# Generated by Django 6.0.6 on 2026-09-12 11:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_placeinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("is_holiday", models.BooleanField(default=False)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("holiday_run", models.PositiveSmallIntegerField(default=0)),
                ("fetched_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="CollectorState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=30)),
                ("key", models.CharField(max_length=255)),
                ("cursor", models.JSONField(default=dict)),
                ("next_run_at", models.DateTimeField(null=True)),
                ("last_success_at", models.DateTimeField(null=True)),
                ("failures", models.PositiveIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=100)),
                ("lease_until", models.DateTimeField(null=True)),
                ("lease_owner", models.CharField(blank=True, max_length=36)),
                ("budget_date", models.DateField(null=True)),
                ("calls", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="CrowdEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("state", models.JSONField(default=dict)),
                ("estimated_at", models.DateTimeField()),
                ("refresh_after", models.DateTimeField()),
                ("model_version", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="ForecastEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issued_at", models.DateTimeField()),
                ("valid_at", models.DateTimeField()),
                ("hours_ahead", models.PositiveSmallIntegerField()),
                ("predicted_score", models.FloatField()),
                ("baseline_score", models.FloatField()),
                ("persistence_score", models.FloatField()),
                ("distribution", models.JSONField(default=list)),
                ("actual_score", models.FloatField(null=True)),
                ("model_version", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric", models.CharField(max_length=30)),
                ("weekday", models.SmallIntegerField()),
                ("hour", models.SmallIntegerField()),
                ("version", models.CharField(max_length=40)),
                ("median", models.FloatField()),
                ("mad", models.FloatField(default=0)),
                ("distribution", models.JSONField(default=list)),
                ("sample_days", models.PositiveSmallIntegerField()),
                ("coverage", models.FloatField()),
                ("context", models.JSONField(default=dict)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric", models.CharField(max_length=30)),
                ("bucket_at", models.DateTimeField()),
                ("value", models.FloatField()),
                ("sample_count", models.PositiveSmallIntegerField()),
                ("quality", models.FloatField(default=1)),
                ("context", models.JSONField(default=dict)),
                ("available_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="PlaceCrowdProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile", models.CharField(default="unknown", max_length=20)),
                ("evidence", models.JSONField(default=dict)),
                ("version", models.CharField(default="profiles-v1", max_length=40)),
                ("grid_x", models.PositiveSmallIntegerField(null=True)),
                ("grid_y", models.PositiveSmallIntegerField(null=True)),
                ("opening_schedule", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TourEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("time_quality", models.CharField(default="date_only", max_length=20)),
                ("size_weight", models.FloatField(default=0.5)),
                ("size_evidence", models.TextField(blank=True)),
                ("size_valid_until", models.DateField(blank=True, null=True)),
                ("raw_data", models.JSONField(default=dict)),
                ("fetched_at", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TransitObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode", models.CharField(max_length=10)),
                ("window_minutes", models.PositiveSmallIntegerField(default=30)),
                ("observed_at", models.DateTimeField()),
                ("fetched_at", models.DateTimeField()),
                (
                    "timestamp_quality",
                    models.CharField(default="collection_only", max_length=20),
                ),
                ("arrivals_min", models.PositiveIntegerField()),
                ("arrivals_max", models.PositiveIntegerField()),
                ("departures_min", models.PositiveIntegerField(null=True)),
                ("departures_max", models.PositiveIntegerField(null=True)),
                ("fingerprint", models.CharField(max_length=64)),
                ("raw_data", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="WeatherSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grid_x", models.PositiveSmallIntegerField()),
                ("grid_y", models.PositiveSmallIntegerField()),
                ("product", models.CharField(max_length=30)),
                ("issued_at", models.DateTimeField()),
                ("valid_at", models.DateTimeField()),
                ("fetched_at", models.DateTimeField()),
                ("values", models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name="crowdarea",
            name="bounds",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="crowdarea",
            name="geometry",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="crowdarea",
            name="geometry_version",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="crowddata",
            name="fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placecrowdarea",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="placecrowdarea",
            name="match_quality",
            field=models.FloatField(
                default=1.0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="placecrowdarea",
            name="representativeness",
            field=models.FloatField(
                default=0.65,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="placecrowdarea",
            name="valid_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placecrowdarea",
            name="valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placecrowdarea",
            name="verified",
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name="placecrowdarea",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("place",),
                name="one_primary_crowd_area",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectorstate",
            constraint=models.UniqueConstraint(
                fields=("provider", "key"), name="unique_collector_key"
            ),
        ),
        migrations.AddField(
            model_name="crowdestimate",
            name="place",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crowd_snapshot",
                to="places.place",
            ),
        ),
        migrations.AddField(
            model_name="forecastevaluation",
            name="crowd_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="places.crowdarea"
            ),
        ),
        migrations.AddField(
            model_name="forecastevaluation",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="places.place"
            ),
        ),
        migrations.AddField(
            model_name="historicalbaseline",
            name="crowd_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="places.crowdarea"
            ),
        ),
        migrations.AddField(
            model_name="historicalsample",
            name="crowd_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="places.crowdarea"
            ),
        ),
        migrations.AddField(
            model_name="placecrowdprofile",
            name="place",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crowd_profile",
                to="places.place",
            ),
        ),
        migrations.AddIndex(
            model_name="tourevent",
            index=models.Index(
                fields=["active", "end_date", "start_date"],
                name="places_tour_active_50e479_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tourevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_date__lte", models.F("end_date"))),
                name="valid_event_dates",
            ),
        ),
        migrations.AddField(
            model_name="transitobservation",
            name="crowd_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="places.crowdarea"
            ),
        ),
        migrations.AddIndex(
            model_name="weathersnapshot",
            index=models.Index(
                fields=["grid_x", "grid_y", "valid_at", "-issued_at"],
                name="places_weat_grid_x_9b8e42_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="weathersnapshot",
            constraint=models.UniqueConstraint(
                fields=("grid_x", "grid_y", "product", "issued_at", "valid_at"),
                name="unique_weather_issue",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastevaluation",
            constraint=models.UniqueConstraint(
                fields=("place", "issued_at", "hours_ahead"),
                name="unique_forecast_evaluation",
            ),
        ),
        migrations.AddIndex(
            model_name="historicalbaseline",
            index=models.Index(
                fields=["crowd_area", "version", "metric"],
                name="places_hist_crowd_a_6df365_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalbaseline",
            constraint=models.UniqueConstraint(
                fields=("crowd_area", "metric", "weekday", "hour", "version"),
                name="unique_baseline_version",
            ),
        ),
        migrations.AddIndex(
            model_name="historicalsample",
            index=models.Index(
                fields=["crowd_area", "metric", "bucket_at"],
                name="places_hist_crowd_a_45429e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalsample",
            constraint=models.UniqueConstraint(
                fields=("crowd_area", "metric", "bucket_at"),
                name="unique_historical_bucket",
            ),
        ),
        migrations.AddIndex(
            model_name="transitobservation",
            index=models.Index(
                fields=["crowd_area", "mode", "-observed_at"],
                name="places_tran_crowd_a_206717_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="transitobservation",
            constraint=models.UniqueConstraint(
                fields=("crowd_area", "mode", "window_minutes", "observed_at"),
                name="unique_transit_window",
            ),
        ),
        migrations.AddConstraint(
            model_name="transitobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("arrivals_min__lte", models.F("arrivals_max"))),
                name="valid_transit_range",
            ),
        ),
    ]
