# Generated by Django 6.0.6 on 2026-09-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_nationwide_crowd"),
    ]

    operations = [
        migrations.AddField(
            model_name="placecrowdprofile",
            name="last_requested_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
