# Generated by Django 6.0.6 on 2026-09-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_indoor_outdoor_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datajob',
            name='processed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
