# Generated by Django 6.0.6 on 2026-09-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0005_crowd_demand"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="historicalbaseline",
            index=models.Index(
                fields=["crowd_area", "metric", "-period_end"],
                name="places_hist_crowd_a_88980c_idx",
            ),
        ),
    ]
