# Generated by Django 6.0.6 on 2026-09-13 15:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_datajob_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceClassificationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=7)),
                ('method', models.CharField(max_length=24)),
                ('version', models.CharField(max_length=24)),
                ('input_hash', models.CharField(max_length=64)),
                ('quote', models.CharField(max_length=255)),
                ('span_start', models.PositiveIntegerField()),
                ('span_end', models.PositiveIntegerField()),
                ('model', models.CharField(blank=True, max_length=40)),
                ('classified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification_record', to='places.place')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceClassificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_hash', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=40)),
                ('status', models.CharField(default='reserved', max_length=24)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_attempts', to='places.place')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('place', 'input_hash', 'model'), name='unique_place_classification_attempt')],
            },
        ),
    ]
