# Generated by Django 6.0.6 on 2026-09-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_placeclassificationevidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeclassificationattempt',
            name='proposal',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='placeclassificationevidence',
            name='ancillary_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='placeclassificationevidence',
            name='evidence_quotes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='placeclassificationevidence',
            name='previous_label',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='placeclassificationevidence',
            name='previous_source',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='placeclassificationevidence',
            name='primary_activity',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='placeclassificationevidence',
            name='rationale',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='placeclassificationevidence',
            name='scope',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
