# Generated by Django 6.0.6 on 2026-09-12 15:11

import django.db.models.deletion
from django.db import migrations, models


def preserve_legacy_approvals(apps, schema_editor):
    Mapping = apps.get_model('places', 'PlaceCrowdArea')
    Mapping.objects.using(schema_editor.connection.alias).filter(evidence={}).update(
        evidence={'type': 'legacy', 'independent_venue_verification': False})


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0006_baseline_lookup_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecastevaluation",
            name="actual_observed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="forecastevaluation",
            name="actual_received_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="forecastevaluation",
            name="baseline_version",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="forecastevaluation",
            name="input_snapshot",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="forecastevaluation",
            name="scope",
            field=models.CharField(default="legacy_place", max_length=40),
        ),
        migrations.AddField(
            model_name="forecastevaluation",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="placecrowdarea",
            name="evidence",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="forecastevaluation",
            name="place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="places.place",
            ),
        ),
        migrations.AlterField(
            model_name="placecrowdarea",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(preserve_legacy_approvals, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='forecastevaluation',
            constraint=models.UniqueConstraint(
                fields=('crowd_area', 'scope', 'model_version', 'issued_at', 'hours_ahead'),
                condition=models.Q(scope='area_core'), name='unique_area_core_forecast'),
        ),
    ]
