# Generated by Django 6.0.6 on 2026-09-14 00:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_placeclassificationattempt_proposal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceWeatherExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='unknown', max_length=7)),
                ('activity', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(max_length=40)),
                ('reason', models.CharField(max_length=255)),
                ('conflict', models.BooleanField(default=False)),
                ('conflict_reason', models.CharField(blank=True, max_length=255)),
                ('type_code', models.CharField(blank=True, max_length=10)),
                ('type_name', models.CharField(blank=True, max_length=100)),
                ('factor', models.FloatField(default=0)),
                ('version', models.CharField(max_length=24)),
                ('input_hash', models.CharField(max_length=64)),
                ('classified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather_exposure_record', to='places.place')),
            ],
        ),
    ]
