# Generated by Django 6.0.6 on 2026-09-12 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0007_validation_quality"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeanStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="area-mean-v1", max_length=80, unique=True
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("config", models.JSONField(default=dict)),
                ("state", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="MeanEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=24)),
                ("key", models.CharField(max_length=255)),
                ("received_at", models.DateTimeField()),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                ("payload", models.JSONField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["kind", "key", "received_at"],
                        name="places_mean_kind_826f6a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MeanPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_id", models.PositiveIntegerField()),
                ("issued_at", models.DateTimeField()),
                ("valid_at", models.DateTimeField()),
                ("payload", models.JSONField()),
                ("actual", models.FloatField(null=True)),
                ("actual_received_at", models.DateTimeField(null=True)),
                ("status", models.CharField(default="pending", max_length=24)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="places.meanstudy",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["study", "issued_at"],
                        name="places_mean_study_i_127e88_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("study", "area_id", "issued_at", "valid_at"),
                        name="unique_mean_prediction",
                    )
                ],
            },
        ),
    ]
