# Generated by Django 6.0.6 on 2026-09-13 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0008_mean_forecast"),
    ]

    operations = [
        migrations.CreateModel(
            name="HourlyStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=16)),
                ("started_at", models.DateTimeField()),
                ("config", models.JSONField(default=dict)),
                ("state", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="HourlyTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("metric", models.CharField(max_length=24)),
                ("scope", models.CharField(max_length=30)),
                ("mapping", models.JSONField(default=dict)),
                ("priority", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=False)),
                ("selected", models.BooleanField(default=False)),
                ("promoted", models.BooleanField(default=False)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="targets",
                        to="places.hourlystudy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HourlyRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issued_at", models.DateTimeField()),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("inputs", models.JSONField(default=dict)),
                ("parameters", models.JSONField(default=dict)),
                ("phase", models.CharField(default="shadow", max_length=16)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="places.hourlytarget",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HourlyObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observed_at", models.DateTimeField()),
                ("received_at", models.DateTimeField()),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                ("value", models.FloatField()),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                ("raw_path", models.CharField(max_length=255)),
                ("raw_hash", models.CharField(max_length=64)),
                ("details", models.JSONField(default=dict)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="places.hourlytarget",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HourlyDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("payload", models.JSONField(default=dict)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="places.hourlytarget",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HourlyForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_at", models.DateTimeField()),
                ("payload", models.JSONField(default=dict)),
                ("actual", models.FloatField(null=True)),
                ("actual_observed_at", models.DateTimeField(null=True)),
                ("actual_received_at", models.DateTimeField(null=True)),
                ("status", models.CharField(default="pending", max_length=16)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="places.hourlyrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "valid_at"], name="hourly_pending_truth"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "valid_at"), name="hourly_forecast_identity"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="hourlytarget",
            constraint=models.UniqueConstraint(
                fields=("study", "external_id"), name="hourly_target_identity"
            ),
        ),
        migrations.AddIndex(
            model_name="hourlyrun",
            index=models.Index(
                fields=["target", "-issued_at"], name="hourly_latest_run"
            ),
        ),
        migrations.AddConstraint(
            model_name="hourlyrun",
            constraint=models.UniqueConstraint(
                fields=("target", "issued_at"), name="hourly_run_identity"
            ),
        ),
        migrations.AddIndex(
            model_name="hourlyobservation",
            index=models.Index(
                fields=["target", "observed_at", "received_at"],
                name="hourly_obs_lookup",
            ),
        ),
        migrations.AddConstraint(
            model_name="hourlyobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gte", 0)), name="hourly_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="hourlydaily",
            constraint=models.UniqueConstraint(
                fields=("target", "date"), name="hourly_daily_identity"
            ),
        ),
    ]
