# Generated by Django 6.0.6 on 2026-09-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_placeweatherexposure'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeclassificationevidence',
            name='weather_activity',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='placeclassificationevidence',
            name='weather_exposure',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='placeclassificationevidence',
            name='weather_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
