# Generated by Django 6.0.6 on 2026-09-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_placeclassificationevidence_weather_activity_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['latitude', 'longitude'], name='places_plac_latitud_09f61a_idx'),
        ),
        migrations.AddIndex(
            model_name='placesource',
            index=models.Index(fields=['place', 'match_status'], name='places_plac_place_i_60440e_idx'),
        ),
    ]
