# Generated by Django 6.0.6 on 2026-09-16 06:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "places",
            "0009_hourlystudy_hourlytarget_hourlyrun_hourlyobservation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tourevent",
            name="changed_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="tourevent",
            name="content_hash",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="tourevent",
            name="detail_pending",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tourevent",
            name="edition",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="tourevent",
            name="family",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="tourevent",
            name="first_seen_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="tourevent",
            name="source",
            field=models.CharField(default="tour_api", max_length=20),
        ),
        migrations.AddField(
            model_name="tourevent",
            name="source_modified_at",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="tourevent",
            name="source_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tourevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "scheduled"),
                    ("cancelled", "cancelled"),
                    ("unpublished", "unpublished"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tourevent",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tourevent",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="EventExperimentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issued_at", models.DateTimeField()),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("version", models.CharField(max_length=50)),
                ("mode", models.CharField(default="retrospective", max_length=16)),
                ("inputs", models.JSONField(default=dict)),
                ("payload", models.JSONField(default=list)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="places.hourlytarget",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target", "issued_at", "version"),
                        name="unique_event_experiment",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventTargetLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("evidence", models.TextField(blank=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "checked_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="places.tourevent",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="places.hourlytarget",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "target"), name="unique_event_target"
                    )
                ],
            },
        ),
    ]
