# Generated by Django 6.0.6 on 2026-09-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_preferences_companion_inquiry_plan_review_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companion",
            name="time",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="companion",
            name="date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
