# Generated by Django 6.0.6 on 2026-09-17 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_feedback"),
        ("users", "0004_companion_time_alter_companion_date"),
    ]

    operations = []
