# Generated by Django 6.0.6 on 2026-09-17 15:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20260917_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousActor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.CharField(max_length=30)),
                ('withdrawn_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawnEmailHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='purge_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawal_reason_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
