# Generated by Django 6.0.6 on 2026-09-17 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_merge_20260917_1750'),
        ('users', '0006_anonymousactor_withdrawalreason_withdrawnemailhash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='users.anonymousactor'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='users.anonymousactor'),
        ),
        migrations.AddField(
            model_name='recentplace',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recent_places', to='users.anonymousactor'),
        ),
        migrations.AddField(
            model_name='review',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.anonymousactor'),
        ),
        migrations.AddField(
            model_name='reviewlike',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_likes', to='users.anonymousactor'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recentplace',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewlike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('actor', 'place'), name='unique_actor_place_favorite'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('actor__isnull', True)), models.Q(('user__isnull', True), ('actor__isnull', False)), _connector='OR'), name='favorite_user_xor_actor'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('actor__isnull', True)), models.Q(('user__isnull', True), ('actor__isnull', False)), _connector='OR'), name='feedback_user_xor_actor'),
        ),
        migrations.AddConstraint(
            model_name='recentplace',
            constraint=models.UniqueConstraint(fields=('actor', 'place'), name='unique_actor_recent_place'),
        ),
        migrations.AddConstraint(
            model_name='recentplace',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('actor__isnull', True)), models.Q(('user__isnull', True), ('actor__isnull', False)), _connector='OR'), name='recentplace_user_xor_actor'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('actor__isnull', True)), models.Q(('user__isnull', True), ('actor__isnull', False)), _connector='OR'), name='review_user_xor_actor'),
        ),
        migrations.AddConstraint(
            model_name='reviewlike',
            constraint=models.UniqueConstraint(fields=('actor', 'review'), name='unique_actor_review_like'),
        ),
        migrations.AddConstraint(
            model_name='reviewlike',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('actor__isnull', True)), models.Q(('user__isnull', True), ('actor__isnull', False)), _connector='OR'), name='reviewlike_user_xor_actor'),
        ),
    ]
