# Generated by Django 6.0.6 on 2026-09-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_favorite_actor_feedback_actor_recentplace_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
