name: tourist_congestion_frontend
description: 실시간 혼잡도 기반 장소 추천 앱의 Flutter 프런트엔드 기본 틀
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
